### ISSUE TITLE
Project "Family Feud" Debug Error on Visual Studio Code

### ISSUE THREAD

**Issue by PitaLife** [ferdinandhof/familyfeud#1]
I have tried your project. but when I try it doesn't work, give me a solution please

**Comment by ferdinandhof** [comment]
Would you mind giving a bit more info? Which error do you get exactly? Did you do all steps from the readme.

**Comment by PitaLife** [comment]
i'm try

**Comment by ferdinandhof** [comment]
Closed due to inactivity
